drop table user_surveys;
drop table survey_questions;
drop table surveys;
drop table users;
drop table roles;
drop table features;
drop type question_type;
drop type role_permission;
drop extension "uuid-ossp";
