version: "3.8"
services:
  app:
    container_name: launch-list
    depends_on:
      postgres:
        condition: service_healthy
      valkey:
        condition: service_started
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: launchl-dev
    env_file:
      - .env
    ports:
      - "8090:8090"
      - "2345:2345" # debug
      - "8087:8087" # air
    volumes:
      - ./:/app:cached
    networks:
     - launchl-network

  email-worker:
    container_name: ll-email-worker
    image: launchl-dev
    # if you make a seperate air.toml file to run ./cmd/emailer you can make it have hot reload
    command: ["go", "run", "./cmd/emailworker"]
    working_dir: /app
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      valkey:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - launchl-network

  valkey:
    container_name: ll-valkey
    image: valkey/valkey:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - valkey_data:/data
    command: ["valkey-server"]
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - launchl-network

  postgres:
    container_name: ll-db
    image: postgres:15-alpine
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d launchl"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - launchl-network

volumes:
  postgres_data:
  valkey_data:

networks:
  launchl-network:
    driver: bridge
