FROM golang:1.25-alpine as builder

ENV GOTOOLCHAIN=auto \
	CGO_ENABLED=0

RUN apk add --no-cache git make

WORKDIR /app

#RUN mkdir -p /app/tmp && chmod 755 /app/tmp

COPY go.mod go.sum ./

RUN go install github.com/air-verse/air@latest \
	&& apk add --no-cache make

COPY . .

RUN go mod download

EXPOSE 8090

CMD ["air", "-c", ".air.toml"]
