// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.898
package html

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func EmailLayoutHTML(title string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"><meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\"><title>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/domain/templates/html/layout.templ`, Line: 11, Col: 15}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</title><style type=\"text/css\">\n\t\t.preheader {\n\t\t\tdisplay: none !important;\n\t\t\tvisibility: hidden;\n\t\t\tmso-hide: all;\n\t\t\tfont-size: 1px;\n\t\t\tline-height: 1px;\n\t\t\tmax-height: 0;\n\t\t\tmax-width: 0;\n\t\t\topacity: 0;\n\t\t\toverflow: hidden;\n\t\t}\n\n\t\tbody {\n\t\t\tmargin: 0;\n\t\t\tpadding: 0;\n\t\t\tbackground-color: #f4f4f4;\n\t\t\tfont-family: Arial, sans-serif;\n\t\t}\n\n\t\ttable {\n\t\t\tborder-collapse: collapse;\n\t\t}\n\n\t\t.container {\n\t\t\twidth: 100%;\n\t\t\tmax-width: 600px;\n\t\t\tmargin: 0 auto;\n\t\t\tbackground-color: #ffffff;\n\t\t}\n\n\t\t.header {\n\t\t\tbackground-color: #345C72;\n\t\t\tcolor: #ffffff;\n\t\t\ttext-align: center;\n\t\t\tpadding: 20px;\n\t\t}\n\n\t\t.body {\n\t\t\tpadding: 20px;\n\t\t\tfont-size: 16px;\n\t\t\tline-height: 1.6;\n\t\t\tcolor: #555555;\n\t\t}\n\n\t\t.footer {\n\t\t\tbackground-color: #333333;\n\t\t\tcolor: #999999;\n\t\t\ttext-align: center;\n\t\t\tpadding: 20px;\n\t\t}\n\n\t\t.cta {\n\t\t\tbackground-color: #345C72;\n\t\t\tpadding: 10px 20px;\n\t\t\tborder-radius: 5px;\n\t\t\tcolor: #ffffff;\n\t\t\ttext-decoration: none;\n\t\t\tfont-weight: bold;\n\t\t}\n\n\t\t@media screen and (max-width: 600px) {\n\t\t\t.container {\n\t\t\t\twidth: 100% !important;\n\t\t\t\tpadding: 10px !important;\n\t\t\t}\n\t\t}\n\t</style></head><body><span class=\"preheader\">You're on the list—here’s what to do next.</span><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\"><tr><td align=\"center\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</td></tr></table></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
